# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [2]:
!pip install numpy mdutils nbformat
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [5]:
print(np.__version__)
np.show_config()

2.4.4
{
  "Compilers": {
    "c": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "14.2.1",
      "commands": "cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.2.4",
      "commands": "cython"
    },
    "c++": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "14.2.1",
      "commands": "c++"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "linux"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "linux"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.31.188.0",
      "detection method": "pkgconfig",
      "include directory": "/opt/_internal/cpython-3.14.0/lib/python3.14/site-packages/scipy_openblas64/include",
      "lib directory": "/opt/_internal/cpython-3.14.0/lib/pyt

#### 3. Create a null vector of size 10 (★☆☆)

In [9]:
null_vec = np.zeros(10)
print(null_vec)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [16]:
import sys

print(null_vec.nbytes)
print(null_vec.size * null_vec.itemsize)
print(sys.getsizeof(null_vec))

80
80
192


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [18]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [22]:
null_vec_special = np.zeros(10)
null_vec_special[4] = 1

print(null_vec_special)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [23]:
range_vec = np.arange(10, 50)
print(range_vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [24]:
reversed_range = np.flip(range_vec)

print(reversed_range)
print(range_vec)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [29]:
matrix3by3 = np.arange(0, 9)
matrix3by3 = np.reshape(matrix3by3, (3,3))

print(matrix3by3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [30]:
input_arr = np.asarray([1,2,0,0,4,0])
non_zero_indices = np.nonzero(input_arr)

print(non_zero_indices)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [31]:
identity3by3 = np.identity(3)
print(identity3by3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [32]:
randoms = np.random.rand(3, 3, 3)
print(randoms)

[[[0.47212301 0.44444449 0.50191223]
  [0.6447857  0.80156359 0.55886616]
  [0.82285791 0.77789786 0.88268075]]

 [[0.45843056 0.11089881 0.53563891]
  [0.42062782 0.2946355  0.15667394]
  [0.96989832 0.15808703 0.81264382]]

 [[0.49701987 0.66716263 0.22016075]
  [0.96773404 0.02751392 0.64477105]
  [0.80688278 0.99643929 0.31554579]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [36]:
randoms_2d = np.random.rand(10, 10)

print(randoms_2d)

minimum = np.min(randoms_2d)
maximum = np.max(randoms_2d)

print(minimum)
print(maximum)


[[0.80236776 0.00434164 0.09665426 0.0216311  0.92363294 0.60229197
  0.95105959 0.63527875 0.05249142 0.26539044]
 [0.46218142 0.00512738 0.21275331 0.89981948 0.81319859 0.36312817
  0.27174574 0.95940775 0.80015239 0.53574051]
 [0.0823197  0.54939741 0.86874914 0.03267027 0.91674471 0.95428222
  0.68493508 0.07826157 0.02632877 0.74900066]
 [0.99260958 0.19478092 0.09136639 0.60887905 0.09784075 0.18920789
  0.73572312 0.09715328 0.7557308  0.92955047]
 [0.1840729  0.54585043 0.32559845 0.81293459 0.21834951 0.68629061
  0.3450087  0.08134397 0.43592136 0.42106021]
 [0.75936115 0.63178872 0.77859895 0.55405293 0.07550017 0.27942325
  0.47058171 0.1740886  0.2674526  0.64846136]
 [0.47392916 0.7926301  0.35479157 0.85427218 0.72784672 0.01660465
  0.80755782 0.7043447  0.25191816 0.34815223]
 [0.89699546 0.35679861 0.35055589 0.03302636 0.21873749 0.21132392
  0.39891431 0.83309652 0.21148368 0.99692244]
 [0.25388772 0.21988417 0.62642237 0.61735299 0.04605007 0.15910563
  0.58350009

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [38]:
random_30 = np.random.rand(30)
rand_mean = np.mean(random_30)

print(random_30)
print(rand_mean)

[0.26323402 0.17994495 0.66805729 0.8614116  0.086041   0.91544567
 0.06651874 0.62372001 0.44662407 0.88370937 0.13828352 0.66142879
 0.92125596 0.58880226 0.45157145 0.44384781 0.97853614 0.10796546
 0.5924582  0.58150573 0.40754714 0.8613903  0.75720672 0.38945782
 0.75423146 0.88811941 0.55584489 0.31209457 0.71627675 0.83331393]
0.5645281676997785


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [42]:
bordered_vec = np.ones((9, 9))
bordered_vec[1:-1, 1:-1] = 0
print(bordered_vec)

alternative_bordered_vec = np.zeros((9, 9))
alternative_bordered_vec[0, :] = 1
alternative_bordered_vec[-1, :] = 1
alternative_bordered_vec[:, 0] = 1
alternative_bordered_vec[:, -1] = 1

print(alternative_bordered_vec)

[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [52]:
# View output as a scrollable element, otherwise results look weird. Also consider making the DIM smaller

DIM = 9
existing_arr = np.random.rand(DIM * DIM).reshape(DIM, DIM)
print(existing_arr)

bordered_arr = np.concatenate((np.zeros((1, DIM)), existing_arr), axis=0)
bordered_arr = np.concatenate((bordered_arr, np.zeros((1, DIM))), axis=0)
bordered_arr = np.concatenate((np.zeros((DIM+2, 1)), bordered_arr), axis=1)
bordered_arr = np.concatenate((bordered_arr, np.zeros((DIM+2, 1))), axis=1)
print(bordered_arr)


[[0.65615411 0.37142687 0.89693877 0.2394143  0.59927637 0.37670876
  0.14093549 0.83641833 0.5642968 ]
 [0.58487984 0.27870617 0.18231726 0.31267712 0.12810941 0.66772734
  0.42797942 0.75891152 0.82544196]
 [0.50447047 0.33407442 0.54045134 0.30829315 0.21768606 0.40052775
  0.97700077 0.14722091 0.36535112]
 [0.6264451  0.8266256  0.16105897 0.91373008 0.47429261 0.97762212
  0.57234032 0.54164459 0.57565736]
 [0.03757968 0.85270644 0.2124664  0.00319897 0.09833095 0.11223072
  0.58276786 0.92387292 0.84643375]
 [0.39147888 0.99196921 0.29958402 0.35122343 0.7737219  0.20031643
  0.30755895 0.30221315 0.84466901]
 [0.04803819 0.89813823 0.56427002 0.24799044 0.30037271 0.5876403
  0.36038386 0.85669077 0.42227461]
 [0.41614783 0.47309686 0.71563535 0.1542059  0.73373229 0.11130625
  0.40836936 0.0532143  0.42496248]
 [0.13937912 0.91172132 0.10193249 0.36404775 0.56568638 0.7963163
  0.77118787 0.97115818 0.51403043]]
[[0.         0.         0.         0.         0.         0.
  0. 

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [54]:
print(0 * np.nan) # arguable what this should return, as 0 * any number stays 0 (I guess nan is not a number :) ), but nan usually propagates. In this case, result is np.nan
print(np.nan == np.nan) # nan is not equal to anything, so False
print(np.inf > np.nan) # False, all these boolean binary operators with NaN return False. All boolean operators with NaN will return NaN
print(np.nan - np.nan) # np.nan, see above
print(np.nan in set([np.nan])) # True, np.nan gets hashed to the same value. Python then checks reference equality with `is`, which evaluates to `True` for np.nan,
# otherwise it would evaluate equality with `__eq__()`, which would be False (see above)
# Note that this is technically a collision in a hash table/hash set, as the elements are not equal to each other
# There is more weirdness around this, e.g. set([np.nan] * 5) will contain one element, whereas set([np.nan for _ in range(5)]) will contain 5 elements
print(0.3 == 3 * 0.1)  # False, floating point imprecision. Use abs(float1 - float) < EPSILON for a small EPSILON, e.g. 0.00001 for equality of floats
# Note that this being true or false depends somewhat on the number you choose, e.g. 0.5 == 5 * 0.1 might evaluate to true as 0.5 can be expressed
# perfectly in IEEE 754 (0.1 cannot though, this is still `True` on my laptop)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [56]:
print(np.diag([1,2,3,4], -1))

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [70]:
checkerboard = np.zeros(8 * 2)
checkerboard[:8:2] = 1
checkerboard[9::2] = 1
checkerboard = checkerboard.reshape(2, 8)
checkerboard = np.concatenate([checkerboard] * 4, axis=0)

print(checkerboard)


[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [72]:
print(np.unravel_index(100, (6,7,8)))

(np.int64(1), np.int64(5), np.int64(4))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [74]:
print(np.tile(np.array([[0,1], [1,0]]), (4, 4)))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [79]:
random_5by5 = np.random.random((5,5))
print(random_5by5)
print("\n")

print((random_5by5-np.mean(random_5by5))/np.std(random_5by5))


[[0.31433996 0.26631547 0.90494676 0.84524332 0.14768547]
 [0.53380535 0.26511678 0.8359274  0.9816357  0.97330483]
 [0.6569647  0.36680085 0.66411977 0.16937971 0.68588005]
 [0.01311124 0.70732366 0.64584356 0.64560358 0.57618309]
 [0.07208331 0.76372497 0.93517101 0.94571283 0.03350006]]


[[-0.78033717 -0.93414573  1.1112055   0.91999268 -1.3140833 ]
 [-0.07745303 -0.93798477  0.89015649  1.35681801  1.33013663]
 [ 0.31699073 -0.61232014  0.33990636 -1.24460291  0.40959822]
 [-1.7450856   0.47827591  0.28137294  0.28060434  0.05827061]
 [-1.55621512  0.65891298  1.20800504  1.24176746 -1.67978614]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [82]:
rgba_color = np.dtype([('r', np.ubyte), ('g', np.ubyte), ('b', np.ubyte), ('a', np.ubyte)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [85]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12], [13,14,15]])
b = np.array([[1,2],[3,4],[5,6]])

print(np.matmul(a,b))

[[ 22  28]
 [ 49  64]
 [ 76 100]
 [103 136]
 [130 172]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [90]:
to_be_negated = np.random.randint(0, 21, 15)
print(to_be_negated)
print("\n")
to_be_negated[(to_be_negated >= 3) & (to_be_negated <= 8)] *= -1
print(to_be_negated)

[ 2 11  8  2 13 12 12 16  3 10 11 15 17  2  7]


[ 2 11 -8  2 13 12 12 16 -3 10 11 15 17  2 -7]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [91]:
print(sum(range(5), -1)) # Python `sum()` implementation: `-1` is the `start` value which is added to the sum, so -1+0+1+2+3+4 = 9
print(np.sum(range(5), -1)) # numpy `sum()` implementation: `-1` is the `axis`, meaning it uses the last axis, so 0+1+2+3+4 = 10

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [98]:
Z = np.random.randint(0, 5, 5)
print(Z)
print("\n")

print(Z ** Z) # works, element wise exponentiation. Note that 0^0 = 1
print(2 << Z >> 2) # works, element wise bit shift, first to the left, then the right. Note that this in effect rounds to the nearest power of 2, you don't get the original value
print(Z <-Z) # works, gives a numpy array of the same dimension as Z full of `False` (element wise comparison; no number is smaller than the negative of itself)
print(1j * Z) # works, 1j is the imaginary number in python, multiplication is element-wise, so this gives an array of the same dimension as the input, with each value being the complex number 0 + entry * i
print(Z/1/1) # works, just gives Z with the entries being floats (element wise division, then again element wise division)
# print(Z < Z > Z) # In python a < b > c resolves to a < b and b > c, however for numpy arrays `and` is not defined, you'd need to use `np.logical_and`, so this throws at runtime

[1 3 0 0 0]


[ 1 27  1  1  1]
[1 4 0 0 0]
[False False False False False]
[0.+1.j 0.+3.j 0.+0.j 0.+0.j 0.+0.j]
[1. 3. 0. 0. 0.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0)) # Numpy array: [0]
print(np.array(0)/np.array(0)) # Numpy array: [np.nan], resolved by element wise division, also yields a `RuntimeWarning`
print(np.array(0)//np.array(0)) # Resolved by element wise division, yields a `RuntimeWarning`. Integers cannot represent NaN, so in numpy the value in the array is 0
print(np.array([np.nan]).astype(int).astype(float)) # Exact value depends on the platform, for me it's [-9.22337204e+18]. First does the C cast `(int) NaN`, then converts that back to float.

0
nan
0
[-9.22337204e+18]


/tmp/ipykernel_2450055/2289728285.py:2: RuntimeWarning: invalid value encountered in divide
  print(np.array(0)/np.array(0)) # Numpy array: [np.nan], resolved by element wise division
/tmp/ipykernel_2450055/2289728285.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0)//np.array(0)) # Numpy array: [np.nan], resolved by element wise division
/tmp/ipykernel_2450055/2289728285.py:4: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
# Task: round e.g. 0.1 -> 1, -0.1 -> -1, etc

Z = np.random.uniform(-10, 10, 10)
print(Z)
print("\n")

print(np.copysign(np.ceil(np.abs(Z)), Z)) # Copysign: Uses sign of each element in 2nd arg for each element in 1st arg. ceil(abs) rounds away from 0, but loses the sign

[ 9.67956427  2.93981302 -6.24869772 -1.38807279  9.68876954  7.67983861
  9.85671845  5.24363574  1.83724944 -6.95310025]


[10.  3. -7. -2. 10.  8. 10.  6.  2. -7.]


#### 30. How to find common values between two arrays? (★☆☆)

In [107]:
a = np.array([1,2,3,4,5,6])
b = np.array([7,8,6,1,9,10])

print(np.intersect1d(a,b))

[1 6]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [109]:
# Ignore all warnings:
np.seterr(all='ignore')

# Return to normal
np.seterr(all='warn', divide='warn', over='warn', under='warn', invalid='warn')


{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [110]:
print(np.sqrt(-1) == np.emath.sqrt(-1)) # False, np.sqrt(-1) returns NaN, whereas np.emath.sqrt(-1) returns 1j (the complex number i)

False


/tmp/ipykernel_2450055/642621651.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1)) # False, np.sqrt(-1) returns NaN, whereas np.emath.sqrt(-1) returns 1j (the complex number i)


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [111]:
today = np.datetime64('now', 'D') # or by passing just 'today'
yesterday = today + np.timedelta64(-1, 'D')
tomorrow = today + np.timedelta64(1, 'D')

print(yesterday)
print(today)
print(tomorrow)

2026-05-04
2026-05-05
2026-05-06


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [121]:
print(np.arange(np.datetime64('2025-01'), np.datetime64('2025-02'), dtype='datetime64[D]'))

['2025-01-01' '2025-01-02' '2025-01-03' '2025-01-04' '2025-01-05'
 '2025-01-06' '2025-01-07' '2025-01-08' '2025-01-09' '2025-01-10'
 '2025-01-11' '2025-01-12' '2025-01-13' '2025-01-14' '2025-01-15'
 '2025-01-16' '2025-01-17' '2025-01-18' '2025-01-19' '2025-01-20'
 '2025-01-21' '2025-01-22' '2025-01-23' '2025-01-24' '2025-01-25'
 '2025-01-26' '2025-01-27' '2025-01-28' '2025-01-29' '2025-01-30'
 '2025-01-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [128]:
A = np.array([[1.,2,3], [4,5,6]])
B = np.array([[7.,8,9], [10,11,12]])

np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)
print(A)

[[ -4. -10. -18.]
 [-28. -40. -54.]]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [133]:
R = np.random.uniform(0.0, 10.0, size=(3,3))
print(R)

print(np.floor(R))
print(R.astype(int)) # Note this changes the type to int while the others keep it as float. You can chain `.astype(float64)` to keep it as a float
print(R // 1)
print(R - (R % 1))
print(np.trunc(R))

[[3.98121905 8.04730776 4.53619927]
 [1.7105449  7.1246812  9.86661533]
 [6.00516908 6.64144982 1.94150942]]
[[3. 8. 4.]
 [1. 7. 9.]
 [6. 6. 1.]]
[[3 8 4]
 [1 7 9]
 [6 6 1]]
[[3. 8. 4.]
 [1. 7. 9.]
 [6. 6. 1.]]
[[3. 8. 4.]
 [1. 7. 9.]
 [6. 6. 1.]]
[[3. 8. 4.]
 [1. 7. 9.]
 [6. 6. 1.]]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [138]:
nums = np.arange(0, 5).reshape(1, 5)
print(np.repeat(nums, 5, axis=0))

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [144]:
def my_gen():
    for i in range(10):
        yield i

print(np.fromiter(my_gen(), dtype=np.int32))

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [148]:
print(np.linspace(0, 1, endpoint=False, num=11)[1:])

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [153]:
print(np.sort(np.random.random(size=10), axis=0))

[0.0395914  0.12176672 0.29418728 0.35786156 0.44004196 0.50496941
 0.60433349 0.66760651 0.74526859 0.75042547]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
import timeit

to_sum = np.array([1,2,3,4,5,6,7,8,-10])

# Also swap order of timeit operations to ensure there are no cache effects
print("np.add.reduce()")
print(timeit.timeit("np.add.reduce(np.array([1,2,3,4,5,6,7,8,-10]))", setup="import numpy as np"))

print("np.sum()")
print(timeit.timeit("np.sum(np.array([1,2,3,4,5,6,7,8,-10]))", setup="import numpy as np"))


print("Correctness:")
print(np.sum(to_sum))
print(np.add.reduce(to_sum))

np.add.reduce()
2.595482144970447
np.sum()
4.508793408051133
Correctness:
26
26


#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [ ]:
A = np.array([1,2,3,4])
B = np.array([1,2,0,4])

print(np.allclose(A,B,equal_nan=True)) #For floats

False


#### 43. Make an array immutable (read-only) (★★☆)

In [164]:
A = np.array([1,2,3,4])
print(A)
A[1] = -4.0
print(A)
A.flags['WRITEABLE'] = False
A[2] = -1.0

[1 2 3 4]
[ 1 -4  3  4]


ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [173]:
A = np.random.random(size=(10,2))
print(A)
polar_X = np.sqrt(np.sum(np.square(A), axis=1))
print(polar_X)
polar_Y = np.arctan2(A[:,1], A[:, 0])
print(polar_Y)
polar_A = np.concatenate((polar_X.reshape(10, 1), polar_Y.reshape(10, 1)), axis=1)
print(polar_A)

[[0.82527895 0.62134762]
 [0.24504956 0.33961929]
 [0.2994809  0.81695977]
 [0.74747985 0.03298568]
 [0.55827553 0.11657657]
 [0.37718052 0.10023187]
 [0.01969612 0.67619086]
 [0.72372604 0.94086856]
 [0.05899836 0.30127878]
 [0.90053049 0.36832804]]
[1.0330335  0.41879655 0.87012187 0.74820731 0.57031716 0.39027115
 0.67647766 1.18701855 0.30700115 0.97294435]
[0.64535074 0.94575852 1.21942816 0.04410057 0.20585744 0.25973684
 1.54167651 0.91511339 1.37741697 0.38825137]
[[1.0330335  0.64535074]
 [0.41879655 0.94575852]
 [0.87012187 1.21942816]
 [0.74820731 0.04410057]
 [0.57031716 0.20585744]
 [0.39027115 0.25973684]
 [0.67647766 1.54167651]
 [1.18701855 0.91511339]
 [0.30700115 1.37741697]
 [0.97294435 0.38825137]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [174]:
v = np.random.random(size=10)
print(v)
v[np.argmax(v, axis=0)] = 0
print(v)

[0.12836844 0.39590956 0.11063756 0.26470805 0.82201532 0.7858573
 0.12014441 0.78651664 0.56554697 0.99020733]
[0.12836844 0.39590956 0.11063756 0.26470805 0.82201532 0.7858573
 0.12014441 0.78651664 0.56554697 0.        ]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [186]:
NUM_SAMPLES = 5
xs = np.linspace(0, 1, NUM_SAMPLES)
ys = np.linspace(0, 1, NUM_SAMPLES)

grid_xs, grid_ys = np.meshgrid(xs, ys)
print(xs)
print(ys)
print(grid_xs)
print(grid_ys)

result = np.zeros((NUM_SAMPLES, NUM_SAMPLES), [('x', float), ('y', float)])
print(result)

result['x'] = grid_xs
result['y'] = grid_ys

print(result)

[0.   0.25 0.5  0.75 1.  ]
[0.   0.25 0.5  0.75 1.  ]
[[0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]]
[[0.   0.   0.   0.   0.  ]
 [0.25 0.25 0.25 0.25 0.25]
 [0.5  0.5  0.5  0.5  0.5 ]
 [0.75 0.75 0.75 0.75 0.75]
 [1.   1.   1.   1.   1.  ]]
[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]]
[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [196]:
x = np.array([1.0,2,3,4,5,6])
y = np.array([7.0,8,9,10,11,12])

print(np.reciprocal(np.subtract(np.repeat(x.reshape((1,6)), 6, axis=0), np.repeat(y.reshape((6,1)), 6, axis=1))))
# Note: This was my own solution, after reading the documentation.
# The sample solution is likely more efficient, using `np.subtract.outer(x, y)` to avoid using `reshape` and `repeat`

[[-0.16666667 -0.2        -0.25       -0.33333333 -0.5        -1.        ]
 [-0.14285714 -0.16666667 -0.2        -0.25       -0.33333333 -0.5       ]
 [-0.125      -0.14285714 -0.16666667 -0.2        -0.25       -0.33333333]
 [-0.11111111 -0.125      -0.14285714 -0.16666667 -0.2        -0.25      ]
 [-0.1        -0.11111111 -0.125      -0.14285714 -0.16666667 -0.2       ]
 [-0.09090909 -0.1        -0.11111111 -0.125      -0.14285714 -0.16666667]]


#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

In [201]:
# These each have a .max and .min that can be accessed to get the numerical value
print(np.iinfo(np.int32))
print(np.finfo(np.float32))

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

Machine parameters for float32
---------------------------------------------------------------
precision = 6   resolution = 1e-06
machep = -23   eps =        1.1920929e-07
negep =  -24   epsneg =     5.9604645e-08
minexp = -126   tiny =       1.1754944e-38
maxexp = 128   max =        3.4028235e+38
nexp =   8   min =        -max
smallest_normal = 1.1754944e-38   smallest_subnormal = 1e-45
---------------------------------------------------------------



#### 49. How to print all the values of an array? (★★☆)

In [204]:
A = np.zeros((100, 11))
print(A)

np.set_printoptions(threshold=sys.maxsize, edgeitems=sys.maxsize)
print(A)

# Restore defaults
np.set_printoptions(edgeitems=3, infstr='inf', linewidth=75, nanstr='nan', precision=8, suppress=False, threshold=1000, formatter=None)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [207]:
scalar = 1.3
A = np.array([1.0, -1.3, -2.0, 1.1, 1.3001])
print(A[np.argmin(np.abs(A - scalar))])

1.3001


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [213]:
color_and_pos = np.dtype([('x', np.int32), ('y', np.int32), ('r', np.ubyte), ('g', np.ubyte), ('b', np.ubyte)])


a = np.array([(0, 0, 255, 255, 255), (1, 1, 128, 128, 128)], dtype=color_and_pos)
print(a)
# Note: Sample solution splits the data type into a position and color subtype, better encapsulation

[(0, 0, 255, 255, 255) (1, 1, 128, 128, 128)]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [230]:
random_coords = np.random.random(size=(100, 2))
diffs = random_coords[:, None, :] - random_coords[None, :, :]
print(np.sqrt(np.sum(np.square(diffs), axis=2)))
# Very different from the sample solution. Scipy apparently has a premade function for just this problem

[[0.         0.63457023 0.16133559 ... 0.3051526  0.47206326 0.3006283 ]
 [0.63457023 0.         0.51101993 ... 0.32944473 0.20066754 0.48784948]
 [0.16133559 0.51101993 0.         ... 0.19500729 0.32921417 0.14791007]
 ...
 [0.3051526  0.32944473 0.19500729 ... 0.         0.18424194 0.24400351]
 [0.47206326 0.20066754 0.32921417 ... 0.18424194 0.         0.28762585]
 [0.3006283  0.48784948 0.14791007 ... 0.24400351 0.28762585 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

In [245]:
float_arr = np.array([1.0, 2.0, 3.0]).astype(np.float32)
print(float_arr)
arr_view = float_arr.view(np.int32)
arr_view[:] = float_arr
print(arr_view)

[1. 2. 3.]
[1 2 3]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [249]:
from io import StringIO

s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
input_file = np.genfromtxt(s, delimiter=",", usemask=True)
print(input_file)
# Note: gives a masked array with masks for the slots that aren't filled in. Not setting `usemask` will give NaN in those spots

[[1.0 2.0 3.0 4.0 5.0]
 [6.0 -- -- 7.0 8.0]
 [-- -- 9.0 10.0 11.0]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [251]:
a = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
for index, val in np.ndenumerate(a):
    print(index, val)

(0, 0) 1.0
(0, 1) 2.0
(0, 2) 3.0
(1, 0) 4.0
(1, 1) 5.0
(1, 2) 6.0


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [263]:
samples = np.linspace(-1, 1, num=20)
grid_x, grid_y = np.meshgrid(samples, samples)
sigma = 1.0
mu = 0.0
squared = np.square(grid_x-mu) + np.square(grid_y-mu)
print(np.exp(-squared/(2*sigma*sigma)))

[[0.36787944 0.40645705 0.44413161 0.47995064 0.51294327 0.54216312
  0.56673297 0.58588835 0.59901696 0.60569117 0.60569117 0.59901696
  0.58588835 0.56673297 0.54216312 0.51294327 0.47995064 0.44413161
  0.40645705 0.36787944]
 [0.40645705 0.4490801  0.49070539 0.53028057 0.56673297 0.59901696
  0.62616332 0.64732742 0.66183276 0.66920687 0.66920687 0.66183276
  0.64732742 0.62616332 0.59901696 0.56673297 0.53028057 0.49070539
  0.4490801  0.40645705]
 [0.44413161 0.49070539 0.53618893 0.57943234 0.61926352 0.65453991
  0.68420248 0.70732828 0.72317812 0.73123573 0.73123573 0.72317812
  0.70732828 0.68420248 0.65453991 0.61926352 0.57943234 0.53618893
  0.49070539 0.44413161]
 [0.47995064 0.53028057 0.57943234 0.62616332 0.66920687 0.70732828
  0.73938312 0.76437402 0.78150214 0.79020959 0.79020959 0.78150214
  0.76437402 0.73938312 0.70732828 0.66920687 0.62616332 0.57943234
  0.53028057 0.47995064]
 [0.51294327 0.56673297 0.61926352 0.66920687 0.7152093  0.75595125
  0.79020959 0.8

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [269]:
z = np.zeros((5,5))
ps = np.array([1.0, 3.0, -2.0])

np.put(z, np.random.choice(z.size, size=ps.size), ps) # Could set replace=False to avoid overwriting an element from ps with another one
print(z)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  3.]
 [ 0.  0.  0.  1. -2.]
 [ 0.  0.  0.  0.  0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [281]:
m = np.random.random(size=(2,3))
print(m)
print("\n")

m -= np.mean(m, axis=1, keepdims=True)
print(m)

[[0.01888792 0.74760739 0.60041143]
 [0.07468759 0.16620662 0.68887169]]


[[-0.43674766  0.29197181  0.14477585]
 [-0.23523438 -0.14371535  0.37894972]]


#### 59. How to sort an array by the nth column? (★★☆)

In [ ]:
m = np.random.random(size=(4,6))
n=3
print(m)
print("\n")

sorted_m = m[m[:, n].argsort(axis=0)] # use argsort to get index order in sorted order, then use that view of the array
print(sorted_m)

[[0.87617681 0.11650029 0.55278006 0.99530682 0.54433155 0.28762472]
 [0.87064813 0.46294974 0.02842858 0.67315283 0.42184627 0.31956083]
 [0.29365673 0.71507754 0.97699562 0.18661609 0.23523084 0.68318576]
 [0.92371106 0.04829611 0.40178504 0.46215553 0.95517072 0.59743392]]


[[0.29365673 0.71507754 0.97699562 0.18661609 0.23523084 0.68318576]
 [0.92371106 0.04829611 0.40178504 0.46215553 0.95517072 0.59743392]
 [0.87064813 0.46294974 0.02842858 0.67315283 0.42184627 0.31956083]
 [0.87617681 0.11650029 0.55278006 0.99530682 0.54433155 0.28762472]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [289]:
#z = np.random.random((2,3)) # evaluates to False
z=np.empty((1,2), dtype=object)
print((~z.any(axis=0)).any())

True


#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)